---
version: 2
jobs:
  build:
    docker:
      # https://github.com/haskell-works/stack-build/blob/master/minimal/Dockerfile
      - image: quay.io/haskell_works/stack-build-minimal
    environment:
      STACK_ARGUMENTS: --no-terminal
    steps:
      - checkout
      - run:
          name: Digest
          command: |
            git ls-files | xargs md5sum > digest
      - restore_cache:
          keys:
            # TODO: stack templates get confused, replace with curlies here
            - v2-[[ .Branch ]]-[[ checksum "digest" ]]
            - v2-[[ .Branch ]]-
            - v2-master-
      - run:
          name: Upgrade Stack
          command: stack upgrade
      - run:
          name: Dependencies
          command: make setup
      - run:
          name: Build
          command: make build
      - save_cache:
          # TODO: stack templates get confused, replace with curlies here
          key: v2-[[ .Branch ]]-[[ checksum "digest" ]]
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Lint
          command: make lint
      - run:
          name: Test
          command: make test
